# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_carousel', '0003_auto_20180716_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owlcarousel',
            name='carousel_ride',
            field=models.CharField(choices=[('carousel', 'carousel'), ('false', 'off')], default='carousel', help_text='Autoplays the owlcarousel after the user manually cycles the first item. If "owlcarousel", autoplays the owlcarousel on load.', max_length=255, verbose_name='Ride'),
        ),
    ]
